type Parallel = {
  brandId: string,
  year: number;
  name: string;
  printRun?: number;
  ssp?: boolean;
};

const PARALLELS: Parallel[] = [

    // 2014
    { brandId: "o-pee-chee-platinum-hockey", year: 2014, name: "Rainbow", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2014, name: "Rainbow Trax", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2014, name: "White Ice", printRun: 199, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2014, name: "Red Prism", printRun: 139, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2014, name: "Blue Cubes", printRun: 65, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2014, name: "Seismic Gold", printRun: 50, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2014, name: "Black Ice", printRun: 25, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2014, name: "Golden Treasures", printRun: 1, },

    // 2015
    { brandId: "o-pee-chee-platinum-hockey", year: 2015, name: "Rainbow", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2015, name: "White Ice", printRun: 199, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2015, name: "Red Prism", printRun: 149, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2015, name: "Black Ice", printRun: 99, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2015, name: "Blue Cubes", printRun: 75, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2015, name: "Seismic Gold", printRun: 50, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2015, name: "Purple", printRun: 25, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2015, name: "Emerald Surge", printRun: 10, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2015, name: "Golden Treasures", printRun: 1, },

    // 2016
    { brandId: "o-pee-chee-platinum-hockey", year: 2016, name: "Rainbow", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2016, name: "Ice Blue Traxx", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2016, name: "Red Prism", printRun: 199, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2016, name: "Blue Cubes", printRun: 99, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2016, name: "Seismic Gold", printRun: 50, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2016, name: "Orange Checkers", printRun: 25, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2016, name: "Emerald Surge", printRun: 10, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2016, name: "Golden Treasures", printRun: 1, },

    // 2017
    { brandId: "o-pee-chee-platinum-hockey", year: 2017, name: "Rainbow", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2017, name: "Violet Pixels", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2017, name: "Red Prism", printRun: 199, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2017, name: "Blue Cubes", printRun: 99, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2017, name: "Seismic Gold", printRun: 50, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2017, name: "Orange Checkers", printRun: 25, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2017, name: "Emerald Surge", printRun: 10, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2017, name: "Golden Treasures", printRun: 1, },

    // 2018
    { brandId: "o-pee-chee-platinum-hockey", year: 2018, name: "Rainbow", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2018, name: "Violet Pixels", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2018, name: "Red Prism", printRun: 199, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2018, name: "Arctic Freeze", printRun: 79, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2018, name: "Seismic Gold", printRun: 50, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2018, name: "Orange Checkers", printRun: 25, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2018, name: "Emerald Surge", printRun: 10, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2018, name: "Golden Treasures", printRun: 1, },

    // 2019
    { brandId: "o-pee-chee-platinum-hockey", year: 2019, name: "Rainbow", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2019, name: "Matte Pink", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2019, name: "Violet Pixels", printRun: 399, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2019, name: "Red Prism", printRun: 199, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2019, name: "Arctic Freeze", printRun: 99, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2019, name: "Seismic Gold", printRun: 50, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2019, name: "Orange Checkers", printRun: 25, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2019, name: "Emerald Surge", printRun: 10, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2019, name: "Golden Treasures", printRun: 1, },

    // 2020
    { brandId: "o-pee-chee-platinum-hockey", year: 2020, name: "Rainbow", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2020, name: "Matte Pink", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2020, name: "Blue Surge", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2020, name: "Red Surge", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2020, name: "Yellow Surge", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2020, name: "Aquamarine", printRun: 499, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2020, name: "Violet Pixels", printRun: 399, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2020, name: "Yellow Traxx", printRun: 249, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2020, name: "Red Prism", printRun: 199, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2020, name: "Arctic Freeze", printRun: 99, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2020, name: "Cosmic", printRun: 65, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2020, name: "Seismic Gold", printRun: 50, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2020, name: "Orange Checkers", printRun: 25, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2020, name: "Emerald Surge", printRun: 10, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2020, name: "Golden Treasures", printRun: 1, },

    // 2021
    { brandId: "o-pee-chee-platinum-hockey", year: 2021, name: "Rainbow", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2021, name: "Matte Pink", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2021, name: "Blue Surge", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2021, name: "Red Surge", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2021, name: "Yellow Surge", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2021, name: "Hot Magma", printRun: 499, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2021, name: "Violet Pixels", printRun: 299, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2021, name: "Red Prism", printRun: 199, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2021, name: "Arctic Freeze", printRun: 99, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2021, name: "Cosmic", printRun: 65, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2021, name: "Seismic Gold", printRun: 50, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2021, name: "Orange Checkers", printRun: 25, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2021, name: "Emerald Surge", printRun: 10, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2021, name: "Golden Treasures", printRun: 1, },

    // 2022
    { brandId: "o-pee-chee-platinum-hockey", year: 2022, name: "Rainbow", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2022, name: "Matte Pink", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2022, name: "Yellow Surge", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2022, name: "Hot Magma", printRun: 499, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2022, name: "Liquid Metal", printRun: 349, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2022, name: "Violet Pixels", printRun: 299, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2022, name: "Red Prism", printRun: 199, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2022, name: "Aquamarine", printRun: 149, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2022, name: "Arctic Freeze", printRun: 99, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2022, name: "Cosmic", printRun: 65, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2022, name: "Seismic Gold", printRun: 50, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2022, name: "Orange Checkers", printRun: 25, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2022, name: "Emerald Surge", printRun: 10, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2022, name: "Golden Treasures", printRun: 1, },

    // 2023
    { brandId: "o-pee-chee-platinum-hockey", year: 2023, name: "Rainbow", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2023, name: "Matte Pink", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2023, name: "Yellow Surge", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2023, name: "Pond Hockey", ssp: true, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2023, name: "Liquid Metal", printRun: 349, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2023, name: "Violet Pixels", printRun: 299, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2023, name: "Red Prism", printRun: 199, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2023, name: "Blue Fragments", printRun: 125, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2023, name: "Arctic Freeze", printRun: 99, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2023, name: "Cosmic", printRun: 65, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2023, name: "Seismic Gold", printRun: 50, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2023, name: "Orange Checkers", printRun: 25, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2023, name: "Emerald Surge", printRun: 10, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2023, name: "Bioluminescence", printRun: 5, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2023, name: "Golden Treasures", printRun: 1, },

    // 2024
    { brandId: "o-pee-chee-platinum-hockey", year: 2024, name: "Rainbow", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2024, name: "Pink Magma", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2024, name: "Yellow Surge", },
    { brandId: "o-pee-chee-platinum-hockey", year: 2024, name: "Liquid Metal", printRun: 349, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2024, name: "Violet Pixels", printRun: 299, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2024, name: "Red Prism", printRun: 199, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2024, name: "Blue Fragments", printRun: 125, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2024, name: "Arctic Freeze", printRun: 99, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2024, name: "Cosmic", printRun: 65, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2024, name: "Seismic Gold", printRun: 50, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2024, name: "Orange Checkers", printRun: 25, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2024, name: "Emerald Surge", printRun: 10, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2024, name: "Bioluminescence", printRun: 5, },
    { brandId: "o-pee-chee-platinum-hockey", year: 2024, name: "Golden Treasures", printRun: 1, },
    
    // 2016
    { brandId: "panini-phoenix-football", year: 2016, name: "Red", },
    { brandId: "panini-phoenix-football", year: 2016, name: "Pink", }, // pink rookie #/299
    { brandId: "panini-phoenix-football", year: 2016, name: "Orange", printRun: 99, },
    { brandId: "panini-phoenix-football", year: 2016, name: "Yellow", printRun: 25, },
    { brandId: "panini-phoenix-football", year: 2016, name: "Green", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2016, name: "Blue", printRun: 1, },

    // 2017
    { brandId: "panini-phoenix-football", year: 2017, name: "Color Burst", },
    { brandId: "panini-phoenix-football", year: 2017, name: "Red", printRun: 299, },
    { brandId: "panini-phoenix-football", year: 2017, name: "Pink", printRun: 199, },
    { brandId: "panini-phoenix-football", year: 2017, name: "Purple", printRun: 149, },
    { brandId: "panini-phoenix-football", year: 2017, name: "Orange", printRun: 99, },
    { brandId: "panini-phoenix-football", year: 2017, name: "Yellow", printRun: 75, },
    { brandId: "panini-phoenix-football", year: 2017, name: "Green", printRun: 25, },
    { brandId: "panini-phoenix-football", year: 2017, name: "Black", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2017, name: "Blue", printRun: 1, },

    // 2018
    { brandId: "panini-phoenix-football", year: 2018, name: "Color Burst", },
    { brandId: "panini-phoenix-football", year: 2018, name: "Red", printRun: 299, },
    { brandId: "panini-phoenix-football", year: 2018, name: "Pink", printRun: 199, },
    { brandId: "panini-phoenix-football", year: 2018, name: "Purple", printRun: 149, },
    { brandId: "panini-phoenix-football", year: 2018, name: "Orange", printRun: 99, },
    { brandId: "panini-phoenix-football", year: 2018, name: "Yellow", printRun: 75, },
    { brandId: "panini-phoenix-football", year: 2018, name: "Green", printRun: 25, },
    { brandId: "panini-phoenix-football", year: 2018, name: "Black", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2018, name: "Blue", printRun: 1, },

    // 2019
    { brandId: "panini-phoenix-football", year: 2019, name: "Color Burst", },
    { brandId: "panini-phoenix-football", year: 2019, name: "Fire Burst", },
    { brandId: "panini-phoenix-football", year: 2019, name: "Silver", },
    { brandId: "panini-phoenix-football", year: 2019, name: "Red", printRun: 299, },
    { brandId: "panini-phoenix-football", year: 2019, name: "Pink", printRun: 199, },
    { brandId: "panini-phoenix-football", year: 2019, name: "Purple", printRun: 149, },
    { brandId: "panini-phoenix-football", year: 2019, name: "Orange", printRun: 99, },
    { brandId: "panini-phoenix-football", year: 2019, name: "Yellow", printRun: 75, },
    { brandId: "panini-phoenix-football", year: 2019, name: "Blue", printRun: 35, },
    { brandId: "panini-phoenix-football", year: 2019, name: "Green", printRun: 25, },
    { brandId: "panini-phoenix-football", year: 2019, name: "Black", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2019, name: "Gold", printRun: 1, },

    // 2020
    { brandId: "panini-phoenix-football", year: 2020, name: "Color Burst", },
    { brandId: "panini-phoenix-football", year: 2020, name: "Fire Burst", },
    { brandId: "panini-phoenix-football", year: 2020, name: "Silver", },
    { brandId: "panini-phoenix-football", year: 2020, name: "Red", printRun: 299, },
    { brandId: "panini-phoenix-football", year: 2020, name: "Pink", printRun: 199, },
    { brandId: "panini-phoenix-football", year: 2020, name: "Teal", printRun: 175, },
    { brandId: "panini-phoenix-football", year: 2020, name: "Purple", printRun: 149, },
    { brandId: "panini-phoenix-football", year: 2020, name: "Orange", printRun: 99, },
    { brandId: "panini-phoenix-football", year: 2020, name: "Yellow", printRun: 75, },
    { brandId: "panini-phoenix-football", year: 2020, name: "Fire & Ice", printRun: 50, },
    { brandId: "panini-phoenix-football", year: 2020, name: "Blue", printRun: 35, },
    { brandId: "panini-phoenix-football", year: 2020, name: "Green", printRun: 25, },
    { brandId: "panini-phoenix-football", year: 2020, name: "Black", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2020, name: "Gold", printRun: 1, },

    // 2021
    { brandId: "panini-phoenix-football", year: 2021, name: "Celestial", },
    { brandId: "panini-phoenix-football", year: 2021, name: "Color Burst", },
    { brandId: "panini-phoenix-football", year: 2021, name: "Fire Burst", },
    { brandId: "panini-phoenix-football", year: 2021, name: "Silver", },
    { brandId: "panini-phoenix-football", year: 2021, name: "Silver Lazer", },
    { brandId: "panini-phoenix-football", year: 2021, name: "White Shimmer", },
    { brandId: "panini-phoenix-football", year: 2021, name: "Red Lazer", printRun: 285, },
    { brandId: "panini-phoenix-football", year: 2021, name: "Red", printRun: 250, },
    { brandId: "panini-phoenix-football", year: 2021, name: "Pink", printRun: 199, },
    { brandId: "panini-phoenix-football", year: 2021, name: "Teal", printRun: 150, },
    { brandId: "panini-phoenix-football", year: 2021, name: "Purple", printRun: 125, },
    { brandId: "panini-phoenix-football", year: 2021, name: "Orange", printRun: 99, },
    { brandId: "panini-phoenix-football", year: 2021, name: "Orange Lazer", printRun: 99, },
    { brandId: "panini-phoenix-football", year: 2021, name: "Yellow", printRun: 75, },
    { brandId: "panini-phoenix-football", year: 2021, name: "Fire & Ice", printRun: 50, },
    { brandId: "panini-phoenix-football", year: 2021, name: "Fire & Ice Lazer", printRun: 50, },
    { brandId: "panini-phoenix-football", year: 2021, name: "Blue", printRun: 35, },
    { brandId: "panini-phoenix-football", year: 2021, name: "Green", printRun: 25, },
    { brandId: "panini-phoenix-football", year: 2021, name: "Green Lazer", printRun: 25, },
    { brandId: "panini-phoenix-football", year: 2021, name: "Black", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2021, name: "Black Lazer", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2021, name: "Gold", printRun: 1, },
    { brandId: "panini-phoenix-football", year: 2021, name: "Gold Lazer", printRun: 1, },

    // 2022
    { brandId: "panini-phoenix-football", year: 2022, name: "Color Burst", },
    { brandId: "panini-phoenix-football", year: 2022, name: "Silver", },
    { brandId: "panini-phoenix-football", year: 2022, name: "Silver Lazer", },
    { brandId: "panini-phoenix-football", year: 2022, name: "Sprinkles", },
    { brandId: "panini-phoenix-football", year: 2022, name: "Red", printRun: 250, },
    { brandId: "panini-phoenix-football", year: 2022, name: "Pink", printRun: 199, },
    { brandId: "panini-phoenix-football", year: 2022, name: "Teal", printRun: 150, },
    { brandId: "panini-phoenix-football", year: 2022, name: "Purple", printRun: 125, },
    { brandId: "panini-phoenix-football", year: 2022, name: "Red Lazer", printRun: 125, },
    { brandId: "panini-phoenix-football", year: 2022, name: "Orange", printRun: 99, },
    { brandId: "panini-phoenix-football", year: 2022, name: "Purple Lazer", printRun: 99, },
    { brandId: "panini-phoenix-football", year: 2022, name: "Orange Lazer", printRun: 75, },
    { brandId: "panini-phoenix-football", year: 2022, name: "Yellow", printRun: 75, },
    { brandId: "panini-phoenix-football", year: 2022, name: "Fire & Ice", printRun: 50, },
    { brandId: "panini-phoenix-football", year: 2022, name: "Fire & Ice Lazer", printRun: 50, },
    { brandId: "panini-phoenix-football", year: 2022, name: "Blue", printRun: 35, },
    { brandId: "panini-phoenix-football", year: 2022, name: "Green", printRun: 25, },
    { brandId: "panini-phoenix-football", year: 2022, name: "Green Lazer", printRun: 25, },
    { brandId: "panini-phoenix-football", year: 2022, name: "Black", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2022, name: "Black Lazer", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2022, name: "Red Mojo", printRun: 10, }, // or less
    { brandId: "panini-phoenix-football", year: 2022, name: "Onyx", printRun: 5, }, // or less
    { brandId: "panini-phoenix-football", year: 2022, name: "Gold", printRun: 1, },
    { brandId: "panini-phoenix-football", year: 2022, name: "Gold Lazer", printRun: 1, },

    // 2023
    { brandId: "panini-phoenix-football", year: 2023, name: "Color Burst", },
    { brandId: "panini-phoenix-football", year: 2023, name: "Dream Weaver", },
    { brandId: "panini-phoenix-football", year: 2023, name: "Silver", },
    { brandId: "panini-phoenix-football", year: 2023, name: "Silver Seismic", },
    { brandId: "panini-phoenix-football", year: 2023, name: "White Shimmer", },
    { brandId: "panini-phoenix-football", year: 2023, name: "Fire Burst", printRun: 340, },
    { brandId: "panini-phoenix-football", year: 2023, name: "Red", printRun: 199, },
    { brandId: "panini-phoenix-football", year: 2023, name: "Red Seismic", printRun: 199, },
    { brandId: "panini-phoenix-football", year: 2023, name: "Pink", printRun: 175, },
    { brandId: "panini-phoenix-football", year: 2023, name: "Lava", printRun: 150, },
    { brandId: "panini-phoenix-football", year: 2023, name: "Purple Seismic", printRun: 125, },
    { brandId: "panini-phoenix-football", year: 2023, name: "Teal", printRun: 125, },
    { brandId: "panini-phoenix-football", year: 2023, name: "Orange Seismic", printRun: 99, },
    { brandId: "panini-phoenix-football", year: 2023, name: "Purple", printRun: 99, },
    { brandId: "panini-phoenix-football", year: 2023, name: "Orange", printRun: 75, },
    { brandId: "panini-phoenix-football", year: 2023, name: "Fire & Ice Seismic", printRun: 50, },
    { brandId: "panini-phoenix-football", year: 2023, name: "Yellow", printRun: 50, },
    { brandId: "panini-phoenix-football", year: 2023, name: "Fire & Ice", printRun: 35, },
    { brandId: "panini-phoenix-football", year: 2023, name: "Blue", printRun: 25, },
    { brandId: "panini-phoenix-football", year: 2023, name: "Green Seismic", printRun: 25, },
    { brandId: "panini-phoenix-football", year: 2023, name: "Green", printRun: 15, },
    { brandId: "panini-phoenix-football", year: 2023, name: "Black", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2023, name: "Black Seismic", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2023, name: "Red Pandora", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2023, name: "Onyx", printRun: 5, },
    { brandId: "panini-phoenix-football", year: 2023, name: "Gold", printRun: 1, },
    { brandId: "panini-phoenix-football", year: 2023, name: "Gold Seismic", printRun: 1, },

    // 2024
    { brandId: "panini-phoenix-football", year: 2024, name: "Hyper", },
    { brandId: "panini-phoenix-football", year: 2024, name: "Ice", },
    { brandId: "panini-phoenix-football", year: 2024, name: "International", },
    { brandId: "panini-phoenix-football", year: 2024, name: "Lazer", },
    { brandId: "panini-phoenix-football", year: 2024, name: "Orange", },
    { brandId: "panini-phoenix-football", year: 2024, name: "Orange Fade", },
    { brandId: "panini-phoenix-football", year: 2024, name: "Orange Hyper", },
    { brandId: "panini-phoenix-football", year: 2024, name: "Orange Lazer", },
    { brandId: "panini-phoenix-football", year: 2024, name: "Pandora", },
    { brandId: "panini-phoenix-football", year: 2024, name: "Purple", },
    { brandId: "panini-phoenix-football", year: 2024, name: "Purple Fade", },
    { brandId: "panini-phoenix-football", year: 2024, name: "Purple Hyper", },
    { brandId: "panini-phoenix-football", year: 2024, name: "Purple Lazer", },
    { brandId: "panini-phoenix-football", year: 2024, name: "Silver", },
    { brandId: "panini-phoenix-football", year: 2024, name: "Wave", },
    { brandId: "panini-phoenix-football", year: 2024, name: "White Shimmer", },
    { brandId: "panini-phoenix-football", year: 2024, name: "Phoenix", printRun: 399, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Teal Helmet", printRun: 399, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Fire Burst", printRun: 350, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Red Fade", printRun: 299, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Team Logos", printRun: 299, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Blue Fade", printRun: 249, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Pulsar", printRun: 200, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Green Fade", printRun: 199, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Red Lazer", printRun: 199, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Stars", printRun: 180, },
    { brandId: "panini-phoenix-football", year: 2024, name: "NFL Shield", printRun: 150, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Red Hyper", printRun: 140, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Blue Lazer", printRun: 125, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Bronze Fade", printRun: 125, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Gold Fade", printRun: 125, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Red", printRun: 99, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Pink Fade", printRun: 88, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Bronze", printRun: 75, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Teal Fade", printRun: 72, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Blue Hyper", printRun: 70, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Blue", printRun: 50, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Green Lazer", printRun: 50, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Pink", printRun: 40, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Bronze Pandora", printRun: 33, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Green Hyper", printRun: 30, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Teal", printRun: 28, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Green", printRun: 25, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Color Burst", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Gold", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Gold Hyper", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Gold Lazer", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Gold Pandora", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2024, name: "International Gold", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Pink Stars", printRun: 8, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Teal Ice", printRun: 7, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Dream Weaver", printRun: 4, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Black", printRun: 1, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Black Hyper", printRun: 1, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Black Lazer", printRun: 1, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Black Pandora", printRun: 1, },
    { brandId: "panini-phoenix-football", year: 2024, name: "Celestial", printRun: 1, },
    { brandId: "panini-phoenix-football", year: 2024, name: "International Black", printRun: 1, },

    // 2025
    { brandId: "panini-phoenix-football", year: 2025, name: "Silver", },
    { brandId: "panini-phoenix-football", year: 2025, name: "Silver Hyper", },
    { brandId: "panini-phoenix-football", year: 2025, name: "Silver Lava", },
    { brandId: "panini-phoenix-football", year: 2025, name: "Silver Lazer", },
    { brandId: "panini-phoenix-football", year: 2025, name: "Silver Mojo", },
    { brandId: "panini-phoenix-football", year: 2025, name: "Silver Pandora", },
    { brandId: "panini-phoenix-football", year: 2025, name: "Silver Pyramids", },
    { brandId: "panini-phoenix-football", year: 2025, name: "Silver Seismic", },
    { brandId: "panini-phoenix-football", year: 2025, name: "Silver Winter", },
    { brandId: "panini-phoenix-football", year: 2025, name: "White Shimmer", },
    { brandId: "panini-phoenix-football", year: 2025, name: "Red Hyper", printRun: 399, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Red Winter", printRun: 399, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Light Blue Pyramids", printRun: 385, },
    { brandId: "panini-phoenix-football", year: 2025, name: "FireBurst", printRun: 350, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Light Blue Lava", printRun: 325, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Pink Hyper", printRun: 299, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Pink Winter", printRun: 299, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Lime Green Pyramids", printRun: 285, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Purple Hyper", printRun: 249, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Purple Winter", printRun: 249, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Lime Green Lava", printRun: 225, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Teal Pyramids", printRun: 225, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Blue Hyper", printRun: 199, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Blue Winter", printRun: 199, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Red Lazer", printRun: 199, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Wave", printRun: 199, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Orange Pandora", printRun: 189, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Yellow Pyramids", printRun: 185, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Teal Lava", printRun: 175, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Green Hyper", printRun: 149, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Green Winter", printRun: 149, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Phoenix", printRun: 149, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Pink Lazer", printRun: 149, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Bronze Pandora", printRun: 125, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Yellow Lava", printRun: 125, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Orange Hyper", printRun: 99, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Orange Winter", printRun: 99, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Purple Lazer", printRun: 99, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Red", printRun: 99, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Red Seismic", printRun: 99, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Ash Pyramids", printRun: 85, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Light Blue Mojo", printRun: 85, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Pyramids", printRun: 85, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Ash Lava", printRun: 75, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Blue Lazer", printRun: 75, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Lime Green Mojo", printRun: 75, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Pink Seismic", printRun: 75, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Blue", printRun: 50, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Bronze Hyper", printRun: 50, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Bronze Winter", printRun: 50, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Teal Mojo", printRun: 50, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Green", printRun: 49, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Green Lazer", printRun: 49, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Purple Seismic", printRun: 49, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Blue Seismic", printRun: 35, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Orange Lazer", printRun: 35, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Yellow Mojo", printRun: 35, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Ash Mojo", printRun: 25, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Green Seismic", printRun: 25, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Orange Seismic", printRun: 20, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Bronze Lazer", printRun: 15, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Bronze Seismic", printRun: 15, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Color Burst", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Gold", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Gold Hyper", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Gold Lava", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Gold Lazer", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Gold Mojo", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Gold Pandora", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Gold Pyramids", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Gold Seismic", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Gold Winter", printRun: 10, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Dream Weaver", printRun: 4, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Black", printRun: 1, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Black Hyper", printRun: 1, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Black Lava", printRun: 1, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Black Lazer", printRun: 1, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Black Mojo", printRun: 1, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Black Pandora", printRun: 1, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Black Pyramids", printRun: 1, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Black Seismic", printRun: 1, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Black Winter", printRun: 1, },
    { brandId: "panini-phoenix-football", year: 2025, name: "Celestial", printRun: 1, },

    // 2020
    { brandId: "panini-mosaic-football", year: 2020, name: "Mosaic", },
    { brandId: "panini-mosaic-football", year: 2020, name: "Blue Reactive", },
    { brandId: "panini-mosaic-football", year: 2020, name: "Pink Camo", },
    { brandId: "panini-mosaic-football", year: 2020, name: "Genesis", },
    { brandId: "panini-mosaic-football", year: 2020, name: "Gold Reactive", },
    { brandId: "panini-mosaic-football", year: 2020, name: "Green Mosaic", },
    { brandId: "panini-mosaic-football", year: 2020, name: "Green Reactive", },
    { brandId: "panini-mosaic-football", year: 2020, name: "Orange Reactive", },
    { brandId: "panini-mosaic-football", year: 2020, name: "Peacock Choice", },
    { brandId: "panini-mosaic-football", year: 2020, name: "Red Mosaic", },
    { brandId: "panini-mosaic-football", year: 2020, name: "Silver", },
    { brandId: "panini-mosaic-football", year: 2020, name: "Silver No Huddle", },
    { brandId: "panini-mosaic-football", year: 2020, name: "White Sparkle", },
    { brandId: "panini-mosaic-football", year: 2020, name: "Blue Mosaic", printRun: 99, },
    { brandId: "panini-mosaic-football", year: 2020, name: "Red Fusion Choice", printRun: 80, },
    { brandId: "panini-mosaic-football", year: 2020, name: "Blue No Huddle", printRun: 75, },
    { brandId: "panini-mosaic-football", year: 2020, name: "Purple No Huddle", printRun: 50, },
    { brandId: "panini-mosaic-football", year: 2020, name: "Purple Mosaic", printRun: 49, },
    { brandId: "panini-mosaic-football", year: 2020, name: "Orange Fluorescent", printRun: 25, },
    { brandId: "panini-mosaic-football", year: 2020, name: "White Mosaic", printRun: 25, },
    { brandId: "panini-mosaic-football", year: 2020, name: "Gold Fluorescent", printRun: 20, },
    { brandId: "panini-mosaic-football", year: 2020, name: "Pink No Huddle", printRun: 20, },
    { brandId: "panini-mosaic-football", year: 2020, name: "Blue Fluorescent", printRun: 15, },
    { brandId: "panini-mosaic-football", year: 2020, name: "Gold Wave", printRun: 17, }, // veterans /10
    { brandId: "panini-mosaic-football", year: 2020, name: "Gold Mosaic", printRun: 10, }, // veterans /17
    { brandId: "panini-mosaic-football", year: 2020, name: "Gold No Huddle", printRun: 10, },
    { brandId: "panini-mosaic-football", year: 2020, name: "Pink Fluorescent", printRun: 10, },
    { brandId: "panini-mosaic-football", year: 2020, name: "Black Gold Choice", printRun: 8, },
    { brandId: "panini-mosaic-football", year: 2020, name: "Black Mosaic", printRun: 1, },
    { brandId: "panini-mosaic-football", year: 2020, name: "Black No Huddle", printRun: 1, },
    { brandId: "panini-mosaic-football", year: 2020, name: "Nebula Choice", printRun: 1, },

    // 2021
    { brandId: "panini-mosaic-football", year: 2021, name: "Honeycomb" },
    { brandId: "panini-mosaic-football", year: 2021, name: "Mosaic" },
    { brandId: "panini-mosaic-football", year: 2021, name: "Blue Reactive" },
    { brandId: "panini-mosaic-football", year: 2021, name: "Genesis" },
    { brandId: "panini-mosaic-football", year: 2021, name: "Green Mosaic" },
    { brandId: "panini-mosaic-football", year: 2021, name: "Orange Reactive" },
    { brandId: "panini-mosaic-football", year: 2021, name: "Peacock Choice" },
    { brandId: "panini-mosaic-football", year: 2021, name: "Pink Camo" },
    { brandId: "panini-mosaic-football", year: 2021, name: "Red Mosaic" },
    { brandId: "panini-mosaic-football", year: 2021, name: "Red Camo" },
    { brandId: "panini-mosaic-football", year: 2021, name: "Silver" },
    { brandId: "panini-mosaic-football", year: 2021, name: "Silver No Huddle" },
    { brandId: "panini-mosaic-football", year: 2021, name: "Yellow Reactive" },
    { brandId: "panini-mosaic-football", year: 2021, name: "Blue Mosaic", printRun: 99, },
    { brandId: "panini-mosaic-football", year: 2021, name: "Red & Yellow Fusion Choice", printRun: 80, },
    { brandId: "panini-mosaic-football", year: 2021, name: "Blue No Huddle", printRun: 75, },
    { brandId: "panini-mosaic-football", year: 2021, name: "Purple No Huddle", printRun: 50, },
    { brandId: "panini-mosaic-football", year: 2021, name: "Purple Mosaic", printRun: 49, },
    { brandId: "panini-mosaic-football", year: 2021, name: "Orange Fluorescent", printRun: 25, },
    { brandId: "panini-mosaic-football", year: 2021, name: "White Mosaic", printRun: 25, },
    { brandId: "panini-mosaic-football", year: 2021, name: "Pink No Huddle", printRun: 20, },
    { brandId: "panini-mosaic-football", year: 2021, name: "Gold Wave", printRun: 17, },
    { brandId: "panini-mosaic-football", year: 2021, name: "Blue Fluorescent", printRun: 15, },
    { brandId: "panini-mosaic-football", year: 2021, name: "Green Swirl", printRun: 11, },
    { brandId: "panini-mosaic-football", year: 2021, name: "Pink Swirl", printRun: 11, },
    { brandId: "panini-mosaic-football", year: 2021, name: "Gold Mosaic", printRun: 10, },
    { brandId: "panini-mosaic-football", year: 2021, name: "Gold No Huddle", printRun: 10, },
    { brandId: "panini-mosaic-football", year: 2021, name: "Green Fluorescent", printRun: 10, },
    { brandId: "panini-mosaic-football", year: 2021, name: "Pink Fluorescent", printRun: 10, },
    { brandId: "panini-mosaic-football", year: 2021, name: "Red Wave", printRun: 9, },
    { brandId: "panini-mosaic-football", year: 2021, name: "Black Gold Choice", printRun: 8, },
    { brandId: "panini-mosaic-football", year: 2021, name: "Black Mosaic", printRun: 1, },
    { brandId: "panini-mosaic-football", year: 2021, name: "Nebula Choice", printRun: 1, },
    { brandId: "panini-mosaic-football", year: 2021, name: "Black No Huddle", printRun: 1, },

    // 2022
    { brandId: "panini-mosaic-football", year: 2022, name: "Pink Camo", },
    { brandId: "panini-mosaic-football", year: 2022, name: "Genesis", },
    { brandId: "panini-mosaic-football", year: 2022, name: "Green Mosaic", },
    { brandId: "panini-mosaic-football", year: 2022, name: "Honeycomb", },
    { brandId: "panini-mosaic-football", year: 2022, name: "Mosaic", },
    { brandId: "panini-mosaic-football", year: 2022, name: "Silver No Huddle", },
    { brandId: "panini-mosaic-football", year: 2022, name: "Orange Reactive", },
    { brandId: "panini-mosaic-football", year: 2022, name: "Peacock Choice", },
    { brandId: "panini-mosaic-football", year: 2022, name: "Red Mosaic", },
    { brandId: "panini-mosaic-football", year: 2022, name: "Silver", },
    { brandId: "panini-mosaic-football", year: 2022, name: "White Sparkle", },
    { brandId: "panini-mosaic-football", year: 2022, name: "Blue Mosaic", printRun: 99, },
    { brandId: "panini-mosaic-football", year: 2022, name: "Red & Yellow Fusion Choice", printRun: 80, },
    { brandId: "panini-mosaic-football", year: 2022, name: "Blue No Huddle", printRun: 75, },
    { brandId: "panini-mosaic-football", year: 2022, name: "Purple No Huddle", printRun: 50, },
    { brandId: "panini-mosaic-football", year: 2022, name: "Purple Mosaic", printRun: 49, },
    { brandId: "panini-mosaic-football", year: 2022, name: "Orange Fluorescent", printRun: 25, },
    { brandId: "panini-mosaic-football", year: 2022, name: "White Mosaic", printRun: 25, },
    { brandId: "panini-mosaic-football", year: 2022, name: "Pink No Huddle", printRun: 20, },
    { brandId: "panini-mosaic-football", year: 2022, name: "Gold Wave", printRun: 17, },
    { brandId: "panini-mosaic-football", year: 2022, name: "Blue Fluorescent", printRun: 15, },
    { brandId: "panini-mosaic-football", year: 2022, name: "Tessellation Mosaic", printRun: 15, },
    { brandId: "panini-mosaic-football", year: 2022, name: "Green Swirl", printRun: 11, },
    { brandId: "panini-mosaic-football", year: 2022, name: "Pink Swirl", printRun: 11, },
    { brandId: "panini-mosaic-football", year: 2022, name: "Gold Mosaic", printRun: 10, },
    { brandId: "panini-mosaic-football", year: 2022, name: "Gold No Huddle", printRun: 10, },
    { brandId: "panini-mosaic-football", year: 2022, name: "Red Wave", printRun: 9, },
    { brandId: "panini-mosaic-football", year: 2022, name: "Black Gold Choice", printRun: 8, },
    { brandId: "panini-mosaic-football", year: 2022, name: "Black Mosaic", printRun: 1, },
    { brandId: "panini-mosaic-football", year: 2022, name: "Nebula Choice", printRun: 1, },
    { brandId: "panini-mosaic-football", year: 2022, name: "Black No Huddle", printRun: 1, },

    // 2023
    { brandId: "panini-mosaic-football", year: 2023, name: "Mosaic", },
    { brandId: "panini-mosaic-football", year: 2023, name: "Pink Camo", },
    { brandId: "panini-mosaic-football", year: 2023, name: "Red Camo", },
    { brandId: "panini-mosaic-football", year: 2023, name: "Choice Red & Green", }, // Rookies #281-380 only
    { brandId: "panini-mosaic-football", year: 2023, name: "Genesis", },
    { brandId: "panini-mosaic-football", year: 2023, name: "Green Mosaic", },
    { brandId: "panini-mosaic-football", year: 2023, name: "Honeycomb", },
    { brandId: "panini-mosaic-football", year: 2023, name: "Peacock Choice", },
    { brandId: "panini-mosaic-football", year: 2023, name: "Blue Reactive", },
    { brandId: "panini-mosaic-football", year: 2023, name: "Yellow Reactive", },
    { brandId: "panini-mosaic-football", year: 2023, name: "Red Mosaic", },
    { brandId: "panini-mosaic-football", year: 2023, name: "Red Sparkle", },
    { brandId: "panini-mosaic-football", year: 2023, name: "Silver", },
    { brandId: "panini-mosaic-football", year: 2023, name: "Silver No Huddle", },
    { brandId: "panini-mosaic-football", year: 2023, name: "White Sparkle", },
    { brandId: "panini-mosaic-football", year: 2023, name: "Orange Mosaic", printRun: 199, },
    { brandId: "panini-mosaic-football", year: 2023, name: "Blue Mosaic", printRun: 99, },
    { brandId: "panini-mosaic-football", year: 2023, name: "Blue Sparkle", printRun: 96, },
    { brandId: "panini-mosaic-football", year: 2023, name: "Red & Yellow Fusion Choice", printRun: 80, },
    { brandId: "panini-mosaic-football", year: 2023, name: "Blue No Huddle", printRun: 75, },
    { brandId: "panini-mosaic-football", year: 2023, name: "Purple No Huddle", printRun: 50, },
    { brandId: "panini-mosaic-football", year: 2023, name: "Purple Mosaic", printRun: 49, },
    { brandId: "panini-mosaic-football", year: 2023, name: "Orange Fluorescent", printRun: 25, },
    { brandId: "panini-mosaic-football", year: 2023, name: "White Mosaic", printRun: 25, },
    { brandId: "panini-mosaic-football", year: 2023, name: "Gold Sparkle", printRun: 24, },
    { brandId: "panini-mosaic-football", year: 2023, name: "Pink No Huddle", printRun: 20, },
    { brandId: "panini-mosaic-football", year: 2023, name: "Gold Wave", printRun: 17, },
    { brandId: "panini-mosaic-football", year: 2023, name: "Blue Fluorescent", printRun: 15, },
    { brandId: "panini-mosaic-football", year: 2023, name: "Tessellation Mosaic", printRun: 15, },
    { brandId: "panini-mosaic-football", year: 2023, name: "Green Swirl", printRun: 11, },
    { brandId: "panini-mosaic-football", year: 2023, name: "Pink Swirl", printRun: 11, },
    { brandId: "panini-mosaic-football", year: 2023, name: "Gold Mosaic", printRun: 10, },
    { brandId: "panini-mosaic-football", year: 2023, name: "Gold No Huddle", printRun: 10, },
    { brandId: "panini-mosaic-football", year: 2023, name: "Green Fluorescent", printRun: 10, },
    { brandId: "panini-mosaic-football", year: 2023, name: "Pink Fluorescent", printRun: 10, },
    { brandId: "panini-mosaic-football", year: 2023, name: "Red Wave", printRun: 9, },
    { brandId: "panini-mosaic-football", year: 2023, name: "Black Gold Choice", printRun: 8, },
    { brandId: "panini-mosaic-football", year: 2023, name: "Green Sparkle", printRun: 8, },
    { brandId: "panini-mosaic-football", year: 2023, name: "Black Mosaic", printRun: 1, },
    { brandId: "panini-mosaic-football", year: 2023, name: "Black No Huddle", printRun: 1, },
    { brandId: "panini-mosaic-football", year: 2023, name: "Nebula Choice", printRun: 1, },

    // 2024
    { brandId: "panini-mosaic-football", year: 2024, name: "Mosaic", },
    { brandId: "panini-mosaic-football", year: 2024, name: "Blue Reactive", },
    { brandId: "panini-mosaic-football", year: 2024, name: "Pink Camo", },
    { brandId: "panini-mosaic-football", year: 2024, name: "Red Camo", },
    { brandId: "panini-mosaic-football", year: 2024, name: "Genesis", },
    { brandId: "panini-mosaic-football", year: 2024, name: "Green Mosaic", },
    { brandId: "panini-mosaic-football", year: 2024, name: "Honeycomb", },
    { brandId: "panini-mosaic-football", year: 2024, name: "Silver No Huddle", },
    { brandId: "panini-mosaic-football", year: 2024, name: "Peacock Choice", },
    { brandId: "panini-mosaic-football", year: 2024, name: "Red Mosaic", },
    { brandId: "panini-mosaic-football", year: 2024, name: "Red Sparkle", },
    { brandId: "panini-mosaic-football", year: 2024, name: "Silver", },
    { brandId: "panini-mosaic-football", year: 2024, name: "White Sparkle", },
    { brandId: "panini-mosaic-football", year: 2024, name: "Yellow Reactive", },
    { brandId: "panini-mosaic-football", year: 2024, name: "Orange Mosaic", printRun: 199, },
    { brandId: "panini-mosaic-football", year: 2024, name: "Blue Mosaic", printRun: 99, },
    { brandId: "panini-mosaic-football", year: 2024, name: "Blue Sparkle", printRun: 96, },
    { brandId: "panini-mosaic-football", year: 2024, name: "Red & Yellow Fusion Choice", printRun: 80, },
    { brandId: "panini-mosaic-football", year: 2024, name: "Blue No Huddle", printRun: 75, },
    { brandId: "panini-mosaic-football", year: 2024, name: "Purple No Huddle", printRun: 50, },
    { brandId: "panini-mosaic-football", year: 2024, name: "Purple Mosaic", printRun: 49, },
    { brandId: "panini-mosaic-football", year: 2024, name: "Orange Fluorescent", printRun: 25, },
    { brandId: "panini-mosaic-football", year: 2024, name: "White Mosaic", printRun: 25, },
    { brandId: "panini-mosaic-football", year: 2024, name: "Gold Sparkle", printRun: 24, },
    { brandId: "panini-mosaic-football", year: 2024, name: "Pink No Huddle", printRun: 20, },
    { brandId: "panini-mosaic-football", year: 2024, name: "Gold Wave", printRun: 17, },
    { brandId: "panini-mosaic-football", year: 2024, name: "Blue Fluorescent", printRun: 15, },
    { brandId: "panini-mosaic-football", year: 2024, name: "Tessellation Mosaic", printRun: 15, },
    { brandId: "panini-mosaic-football", year: 2024, name: "Green Swirl", printRun: 13, },
    { brandId: "panini-mosaic-football", year: 2024, name: "Pink Swirl", printRun: 13, },
    { brandId: "panini-mosaic-football", year: 2024, name: "Gold Mosaic", printRun: 10, },
    { brandId: "panini-mosaic-football", year: 2024, name: "Green Fluorescent", printRun: 10, },
    { brandId: "panini-mosaic-football", year: 2024, name: "Gold No Huddle", printRun: 10, },
    { brandId: "panini-mosaic-football", year: 2024, name: "Pink Fluorescent", printRun: 10, },
    { brandId: "panini-mosaic-football", year: 2024, name: "Red Wave", printRun: 9, },
    { brandId: "panini-mosaic-football", year: 2024, name: "Black Gold Choice", printRun: 8, },
    { brandId: "panini-mosaic-football", year: 2024, name: "Green Sparkle", printRun: 8, },
    { brandId: "panini-mosaic-football",   year: 2024, name: "Black Mosaic", printRun: 1, },
    { brandId: "panini-mosaic-football", year: 2024, name: "Nebula Choice", printRun: 1, },
    { brandId: "panini-mosaic-football", year: 2024, name: "Black No Huddle", printRun: 1, },

    // 2025
    { brandId: "panini-mosaic-football", year: 2025, name: "Blue Scope", },
    { brandId: "panini-mosaic-football", year: 2025, name: "Honeycomb", },
    { brandId: "panini-mosaic-football", year: 2025, name: "Mosaic", },
    { brandId: "panini-mosaic-football", year: 2025, name: "Pink Camo", },
    { brandId: "panini-mosaic-football", year: 2025, name: "Red Camo", },
    { brandId: "panini-mosaic-football", year: 2025, name: "Peacock Choice", },
    { brandId: "panini-mosaic-football", year: 2025, name: "Red & Green Choice", }, // rookies only
    { brandId: "panini-mosaic-football", year: 2025, name: "Cookies", }, // rookies only
    { brandId: "panini-mosaic-football", year: 2025, name: "Genesis", },
    { brandId: "panini-mosaic-football", year: 2025, name: "Green Mosaic", },
    { brandId: "panini-mosaic-football", year: 2025, name: "Silver No Huddle", },
    { brandId: "panini-mosaic-football", year: 2025, name: "Blue Reactive", },
    { brandId: "panini-mosaic-football", year: 2025, name: "Purple Reactive", },
    { brandId: "panini-mosaic-football", year: 2025, name: "Yellow Reactive", },
    { brandId: "panini-mosaic-football", year: 2025, name: "Red Mosaic", },
    { brandId: "panini-mosaic-football", year: 2025, name: "Red & White Stripe Mosaic", }, // rookies only
    { brandId: "panini-mosaic-football", year: 2025, name: "Purple Scope", },
    { brandId: "panini-mosaic-football", year: 2025, name: "Red Scope", },
    { brandId: "panini-mosaic-football", year: 2025, name: "Red Sparkle", },
    { brandId: "panini-mosaic-football", year: 2025, name: "Silver", },
    { brandId: "panini-mosaic-football", year: 2025, name: "White Sparkle", },
    { brandId: "panini-mosaic-football", year: 2025, name: "Orange Mosaic", printRun: 199, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Silver Knight", printRun: 149, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Blue Mosaic", printRun: 99, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Blue No Huddle", printRun: 99, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Blue Sparkle", printRun: 96, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Red & Yellow Fusion Choice", printRun: 89, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Purple No Huddle", printRun: 50, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Purple Mosaic", printRun: 49, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Red Wave", printRun: 27 }, // rookie /29
    { brandId: "panini-mosaic-football", year: 2025, name: "Orange Fluorescent", printRun: 25, },
    { brandId: "panini-mosaic-football", year: 2025, name: "White Mosaic", printRun: 25, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Gold Sparkle", printRun: 24, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Cherry Blossom", printRun: 20, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Pink No Huddle", printRun: 20, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Blue Fluorescent", printRun: 15, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Tessellation Mosaic", printRun: 15, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Green Spectris", printRun: 13, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Pink Spectris", printRun: 13, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Gold Mosaic", printRun: 10, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Gold Wave", printRun: 10, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Green Fluorescent", printRun: 10, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Gold No Huddle", printRun: 10, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Pink Fluorescent", printRun: 10, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Green Sparkle", printRun: 8, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Black Gold Choice", printRun: 8, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Gold Glitter", printRun: 5, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Black Mosaic", printRun: 1, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Nebula Choice", printRun: 1, },
    { brandId: "panini-mosaic-football", year: 2025, name: "Black No Huddle", printRun: 1, },
];

function compareParalllels(a: Parallel, b: Parallel) {
  if (a.year < b.year) return -1;
  if (a.year > b.year) return 1;

  if (a.printRun && !b.printRun) return -1;
  if (!a.printRun && b.printRun) return 1;
  if (a.printRun && b.printRun) {
    if (a.printRun < b.printRun) return -1;
    if (a.printRun > b.printRun) return 1;
  }

  if (a.ssp && !b.ssp) return -1;
  if (!a.ssp && b.ssp) return 1;

  if (a.name < b.name) return -1;
  if (a.name > b.name) return 1;
  return 0;
}

function getPrintRun(p: Parallel): string {
  if (p.printRun === 1) return '1/1';
  if (p.printRun) return `#/${p.printRun}`;
  if (p.ssp) return 'SSP'
  return '';
}

export function convertParallelsToData(parallels: Parallel[], showDiscontinued = false) {
  const maxYear = Math.max(...parallels.map((p) => p.year));
  const activeParallels = parallels.filter((p) => p.year === maxYear).map((p) => p.name);

  const columns = [
    { type: 'string', id: 'Parallel' },
    { type: 'string', id: 'Print Run' },
    { type: 'date', id: 'Start' },
    { type: 'date', id: 'End' },
  ];

  const rows: (string | Date)[][] = [];
  parallels
    .sort(compareParalllels)
    .filter(p => showDiscontinued || activeParallels.includes(p.name))
    .forEach(p => {
      const printRun = getPrintRun(p);
      const endDate = new Date(p.year + 1, 0, 1);
      const existing = rows.findLast(row => row[0] === p.name && row[1] === printRun && (row[3] as Date).getFullYear() === p.year);
      if (existing) {
        existing[3] = endDate;
      } else {
        rows.push([p.name, printRun, new Date(p.year, 0, 1), endDate]);
      }
    });

  return [columns, ...rows];
}

export function findParallelsByBrand(brandId?: string): Parallel[] {
  return PARALLELS.filter(p => p.brandId === brandId);
}